---
title: "Interactive Graph Examples"
author: "Margaret Brickner"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, we'll practice creating some interactive graphs and tables using built-in datasets in R packages.

- Interactive plots: {plotly}
- Interactive tables: {DT}

```{r, include = FALSE}
# Attach packages: 
library(tidyverse)
library(plotly)
library(DT)

```

### A. Interactive graph of iris dimensions

Using Edgar Anderson's famous 'iris' dataset

```{r, echo = FALSE}

iris_graph <- ggplot(data = iris, aes(x = Petal.Width, y = Petal.Length)) +
  geom_point(aes(size = Sepal.Width, 
                 color = Species), 
             alpha = 0.5) + 
  theme_minimal() + 
  labs(x = "Petal width (cm)", y = "Petal length (cm)", title = "My iris graph")

# iris_graph this could be useful in the future, so I don't totally want to get rid of it. So, I'm commenting it out. If you want to comment out an entire code chunk. You can ad eval = FALSE in the {r} at the top of each coded section 

ggplotly(iris_graph)


```

### Make an interactive table with DT


```{r}
datatable(msleep)
```

